### ISSUE TITLE
[Bugfix] running unsupervised da with dann

### ISSUE THREAD

**Issue by fakedev9999** [virajprabhu/CLUE#3]
```
opt_dis_adapt = optim.Adam(discriminator.parameters(), lr=args.uda_lr, betas=(0.9, 0.999), weight_decay=0)
uda_solver.solve(epoch, discriminator, opt_dis_adapt)
```

In lines 305, 306 in `utils.py`,

> UnboundLocalError: local variable 'discriminator' referenced before assignment
occurs.

Instead of `discriminator`, I think the code should be fixed as `adapt_model.discriminator`.

@virajprabhu Let me know if I got it wrong.

**Comment by virajprabhu** [comment]
You're right, will fix. Thanks!
