### ISSUE TITLE
AttributeError: 'objectview' object has no attribute 'clue_softmax_t'

### ISSUE THREAD

**Issue by rgmey** [virajprabhu/CLUE#5]
Hey there, thanks for the great work
I have a problem implementing the CLUE method, in this file:
https://github.com/virajprabhu/CLUE/blob/main/sample.py
I get the error:
AttributeError: 'objectview' object has no attribute 'clue_softmax_t'
in the class CLUESampling(SamplingStrategy), are you sure the codes are still working and there has not been any changes to them?

**Comment by virajprabhu** [comment]
Should be fixed now, can you pull the latest and try again?
